### ISSUE TITLE
Feature Request: Documentation

### ISSUE THREAD

**Issue by iammerrick** [malkomalko/Cappuccino.tmbundle#1]
It would be helpful if a command was added to search the API documentation. CTL+H is common throughout bundles.

**Comment by hammerdr** [comment]
Just as a stop-gap. There is a nice Mac app called CappKido which allows you to search the API by class, symbol, string names and navigate by other attributes, as well.

http://www.cappkido.eliotis.com/

**Comment by iammerrick** [comment]
Oh thanks! I'm like this. Much appreciated.
